<?php return array (
  'util' => 
  array (
    'u' => 'lutil@mailinator.com',
    'p' => 'qweqwe123',
    'x' => 32,
    'y' => 32,
  ),
  'limitium' => 
  array (
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
    'x' => 32,
    'y' => 32,
  ),
  10 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => '1st Closed Beta server. Slots for 25,000 players.',
    'Id' => 10,
    'Language' => 'en',
    'Name' => 'Closed Beta 1',
    'StartTime' => 1323871200000,
    'Timezone' => 2,
    'Url' => 'http://prodgame02.alliances.commandandconquer.com/10',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'limitium@gmail.com',
  ),
  11 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => '2nd Closed Beta server. Slots for 50,000 players.',
    'Id' => 11,
    'Language' => 'en',
    'Name' => 'Closed Beta 2',
    'StartTime' => 1329123600000,
    'Timezone' => 2,
    'Url' => 'http://prodgame03.alliances.commandandconquer.com/11',
    'x' => 50,
    'y' => 50,
    'p' => 'qweqwe123',
    'u' => 'limitium@gmail.com',
  ),
  12 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => '3rd Closed Beta server. Slots for 25,000 players.',
    'Id' => 12,
    'Language' => 'en',
    'Name' => 'Closed Beta 3',
    'StartTime' => 1330511400000,
    'Timezone' => 2,
    'Url' => 'http://prodgame10.alliances.commandandconquer.com/12',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'limitium@gmail.com',
  ),
  13 => 
  array (
    'AcceptNewPlayer' => false,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 13,
    'Language' => 'en',
    'Name' => 'World 4 (Europe)',
    'StartTime' => 1331719200000,
    'Timezone' => 2,
    'Url' => 'http://prodgame05.alliances.commandandconquer.com/13',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'limitium@gmail.com',
  ),
  14 => 
  array (
    'AcceptNewPlayer' => false,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 14,
    'Language' => 'en',
    'Name' => 'World 5 (USA East Coast)',
    'StartTime' => 1331719200000,
    'Timezone' => -4,
    'Url' => 'http://prodgame05.alliances.commandandconquer.com/14',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'limitium@gmail.com',
  ),
  15 => 
  array (
    'AcceptNewPlayer' => false,
    'Description' => 'Slots für 25,000 Spieler.',
    'Id' => 15,
    'Language' => 'de',
    'Name' => 'Welt 1',
    'StartTime' => 1331719200000,
    'Timezone' => 2,
    'Url' => 'http://prodgame08.alliances.commandandconquer.com/15',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'limitium@gmail.com',
  ),
  16 => 
  array (
    'AcceptNewPlayer' => false,
    'Description' => 'Slots für 25,000 Spieler.',
    'Id' => 16,
    'Language' => 'de',
    'Name' => 'Welt 2',
    'StartTime' => 1332493200000,
    'Timezone' => 2,
    'Url' => 'http://prodgame08.alliances.commandandconquer.com/16',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'limitium@gmail.com',
  ),
  17 => 
  array (
    'AcceptNewPlayer' => false,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 17,
    'Language' => 'en',
    'Name' => 'World 6 (Europe)',
    'StartTime' => 1331899200000,
    'Timezone' => 2,
    'Url' => 'http://prodgame05.alliances.commandandconquer.com/17',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'limitium@gmail.com',
  ),
  18 => 
  array (
    'AcceptNewPlayer' => false,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 18,
    'Language' => 'en',
    'Name' => 'World 7 (Europe)',
    'StartTime' => 1332149400000,
    'Timezone' => 2,
    'Url' => 'http://prodgame05.alliances.commandandconquer.com/18',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'limitium@gmail.com',
  ),
  19 => 
  array (
    'AcceptNewPlayer' => false,
    'Description' => 'Slots für 25,000 Spieler.',
    'Id' => 19,
    'Language' => 'de',
    'Name' => 'Welt 3',
    'StartTime' => 1333353600000,
    'Timezone' => 2,
    'Url' => 'http://prodgame08.alliances.commandandconquer.com/19',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lwelt3@mailinator.com',
  ),
  20 => 
  array (
    'AcceptNewPlayer' => false,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 20,
    'Language' => 'en',
    'Name' => 'World 8 (USA East Coast)',
    'StartTime' => 1332500400000,
    'Timezone' => -4,
    'Url' => 'http://prodgame02.alliances.commandandconquer.com/20',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'limitium@gmail.com',
  ),
  21 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 21,
    'Language' => 'en',
    'Name' => 'World 9 (USA West Coast)',
    'StartTime' => 1332500400000,
    'Timezone' => -7,
    'Url' => 'http://prodgame03.alliances.commandandconquer.com/21',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'limitium@gmail.com',
  ),
  24 => 
  array (
    'AcceptNewPlayer' => false,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 24,
    'Language' => 'en',
    'Name' => 'World 10 (Europe)',
    'StartTime' => 1332586800000,
    'Timezone' => 2,
    'Url' => 'http://prodgame02.alliances.commandandconquer.com/24',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'limitium@gmail.com',
  ),
  25 => 
  array (
    'AcceptNewPlayer' => false,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 25,
    'Language' => 'en',
    'Name' => 'World 11 (Europe)',
    'StartTime' => 1333353600000,
    'Timezone' => 2,
    'Url' => 'http://prodgame03.alliances.commandandconquer.com/25',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lworld11@mailinator.com',
  ),
  26 => 
  array (
    'AcceptNewPlayer' => false,
    'Description' => 'Slots für 25,000 Spieler.',
    'Id' => 26,
    'Language' => 'de',
    'Name' => 'Welt 4',
    'StartTime' => 1336816800700,
    'Timezone' => 2,
    'Url' => 'http://prodgame08.alliances.commandandconquer.com/26',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lwelt4@mailinator.com',
  ),
  27 => 
  array (
    'AcceptNewPlayer' => false,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 27,
    'Language' => 'en',
    'Name' => 'World 12 (Europe)',
    'StartTime' => 1333705500000,
    'Timezone' => 2,
    'Url' => 'http://prodgame10.alliances.commandandconquer.com/27',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lworld12@mailinator.com',
  ),
  28 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 28,
    'Language' => 'en',
    'Name' => 'World 13 (USA East Coast)',
    'StartTime' => 1334325600000,
    'Timezone' => -4,
    'Url' => 'http://prodgame02.alliances.commandandconquer.com/28',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lworld13@mailinator.com',
  ),
  29 => 
  array (
    'AcceptNewPlayer' => false,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 29,
    'Language' => 'en',
    'Name' => 'World 15 (Europe)',
    'StartTime' => 1335970800000,
    'Timezone' => 2,
    'Url' => 'http://prodgame03.alliances.commandandconquer.com/29',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lworld15@mailinator.com',
  ),
  30 => 
  array (
    'AcceptNewPlayer' => false,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 30,
    'Language' => 'en',
    'Name' => 'World 14 (Europe)',
    'StartTime' => 1334560800000,
    'Timezone' => 2,
    'Url' => 'http://prodgame10.alliances.commandandconquer.com/30',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lworld14@mailinator.com',
  ),
  31 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 31,
    'Language' => 'en',
    'Name' => 'World 16 (Europe)',
    'StartTime' => 1337065200430,
    'Timezone' => 2,
    'Url' => 'http://prodgame05.alliances.commandandconquer.com/31',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lworld16@mailinator.com',
  ),
  32 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 32,
    'Language' => 'en',
    'Name' => 'World 17 (USA East Coast)',
    'StartTime' => 1337691600430,
    'Timezone' => -4,
    'Url' => 'http://prodgame02.alliances.commandandconquer.com/32',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'limitium@gmail.com',
  ),
  33 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 33,
    'Language' => 'en',
    'Name' => 'World 18 (Europe)',
    'StartTime' => 1337846400640,
    'Timezone' => 2,
    'Url' => 'http://prodgame03.alliances.commandandconquer.com/33',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'limitium@gmail.com',
  ),
  34 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 34,
    'Language' => 'en',
    'Name' => 'World 19 (USA West Coast)',
    'StartTime' => 1337846400640,
    'Timezone' => -7,
    'Url' => 'http://prodgame10.alliances.commandandconquer.com/34',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'limitium@gmail.com',
  ),
  36 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 36,
    'Language' => 'en',
    'Name' => 'World 21 (Europe)',
    'StartTime' => 1338390000000,
    'Timezone' => 2,
    'Url' => 'http://prodgame10.alliances.commandandconquer.com/36',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'limitium@gmail.com',
  ),
  37 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Emplacements pour 25 000 joueurs.',
    'Id' => 37,
    'Language' => 'fr',
    'Name' => 'Monde 1',
    'StartTime' => 1337846400640,
    'Timezone' => 2,
    'Url' => 'http://prodgame07.alliances.commandandconquer.com/37',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'limitium@gmail.com',
  ),
  38 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slot per 25.000 giocatori.',
    'Id' => 38,
    'Language' => 'it',
    'Name' => 'Mondo 1',
    'StartTime' => 1337846400640,
    'Timezone' => 2,
    'Url' => 'http://prodgame07.alliances.commandandconquer.com/38',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'limitium@gmail.com',
  ),
  39 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Espacios para 25.000 jugadores.',
    'Id' => 39,
    'Language' => 'es',
    'Name' => 'Mundo 1 (España)',
    'StartTime' => 1337846400640,
    'Timezone' => 2,
    'Url' => 'http://prodgame07.alliances.commandandconquer.com/39',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'limitium@gmail.com',
  ),
  40 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Miejsca dla 25 000 graczy.',
    'Id' => 40,
    'Language' => 'pl',
    'Name' => 'Świat 1',
    'StartTime' => 1337846400640,
    'Timezone' => 2,
    'Url' => 'http://prodgame07.alliances.commandandconquer.com/40',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'limitium@gmail.com',
  ),
  41 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Ячейки для 25 000 игроков.
',
    'Id' => 41,
    'Language' => 'ru',
    'Name' => 'Мир 1',
    'StartTime' => 1337846400640,
    'Timezone' => 4,
    'Url' => 'http://prodgame09.alliances.commandandconquer.com/41',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lmir1@mailinator.com',
  ),
  42 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Entradas para 25 000 jogadores.',
    'Id' => 42,
    'Language' => 'pt',
    'Name' => 'Mundo 1 (Portuguesa)',
    'StartTime' => 1337846400640,
    'Timezone' => 1,
    'Url' => 'http://prodgame09.alliances.commandandconquer.com/42',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'limitium@gmail.com',
  ),
  43 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => '25.000 oyuncu alır',
    'Id' => 43,
    'Language' => 'tr',
    'Name' => 'Dünya 1',
    'StartTime' => 1337846400640,
    'Timezone' => 3,
    'Url' => 'http://prodgame09.alliances.commandandconquer.com/43',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'limitium@gmail.com',
  ),
  44 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots voor 25.000 spelers.',
    'Id' => 44,
    'Language' => 'nl',
    'Name' => 'Wereld 1',
    'StartTime' => 1337846400640,
    'Timezone' => 2,
    'Url' => 'http://prodgame09.alliances.commandandconquer.com/44',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'limitium@gmail.com',
  ),
  45 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Espaços para 25.000 jogadores.',
    'Id' => 45,
    'Language' => 'pt',
    'Name' => 'Mundo 1 Brazil',
    'StartTime' => 1337846400640,
    'Timezone' => -3,
    'Url' => 'http://prodgame09.alliances.commandandconquer.com/45',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'limitium@gmail.com',
  ),
  46 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots für 25,000 Spieler.',
    'Id' => 46,
    'Language' => 'de',
    'Name' => 'Welt 5',
    'StartTime' => 1338300000640,
    'Timezone' => 2,
    'Url' => 'http://prodgame07.alliances.commandandconquer.com/46',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lwelt5@mailinator.com',
  ),
  47 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Emplacements pour 25 000 joueurs.',
    'Id' => 47,
    'Language' => 'fr',
    'Name' => 'Monde 2',
    'StartTime' => 1339160400460,
    'Timezone' => 2,
    'Url' => 'http://prodgame06.alliances.commandandconquer.com/47',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'limitium@gmail.com',
  ),
  49 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Espacios para 25.000 jugadores.',
    'Id' => 49,
    'Language' => 'es',
    'Name' => 'Mundo 2 (España)',
    'StartTime' => 1339427100460,
    'Timezone' => 2,
    'Url' => 'http://prodgame12.alliances.commandandconquer.com/49',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'limitium@gmail.com',
  ),
  52 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Ячейки для 25 000 игроков.',
    'Id' => 52,
    'Language' => 'ru',
    'Name' => 'Мир 2',
    'StartTime' => 1340029800000,
    'Timezone' => 4,
    'Url' => 'http://prodgame12.alliances.commandandconquer.com/52',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'limitium@gmail.com',
  ),
  55 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Espaços para 25.000 jogadores.',
    'Id' => 55,
    'Language' => 'pt',
    'Name' => 'Mundo 2 Brazil',
    'StartTime' => 1340370000970,
    'Timezone' => -3,
    'Url' => 'http://prodgame12.alliances.commandandconquer.com/55',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'limitium@gmail.com',
  ),
  56 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 56,
    'Language' => 'en',
    'Name' => 'World 22 (USA East Coast)',
    'StartTime' => 1338652800180,
    'Timezone' => -4,
    'Url' => 'http://prodgame05.alliances.commandandconquer.com/56',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'limitium@gmail.com',
  ),
  57 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 57,
    'Language' => 'en',
    'Name' => 'World 23 (Europe)',
    'StartTime' => 1338832800890,
    'Timezone' => 2,
    'Url' => 'http://prodgame03.alliances.commandandconquer.com/57',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'limitium@gmail.com',
  ),
  58 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots für 25,000 Spieler.',
    'Id' => 58,
    'Language' => 'de',
    'Name' => 'Welt 6',
    'StartTime' => 1339160400460,
    'Timezone' => 2,
    'Url' => 'http://prodgame07.alliances.commandandconquer.com/58',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lwelt6@mailinator.com',
  ),
  59 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots for 25,000 players.#',
    'Id' => 59,
    'Language' => 'en',
    'Name' => 'World 24 (Europe)',
    'StartTime' => 1339427100460,
    'Timezone' => 2,
    'Url' => 'http://prodgame11.alliances.commandandconquer.com/59',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'limitium@gmail.com',
  ),
  60 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 60,
    'Language' => 'en',
    'Name' => 'World 25 (USA West Coast)',
    'StartTime' => 1339581600440,
    'Timezone' => -7,
    'Url' => 'http://prodgame11.alliances.commandandconquer.com/60',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'limitium@gmail.com',
  ),
  61 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 61,
    'Language' => 'en',
    'Name' => 'World 26 (USA East Coast)',
    'StartTime' => 1339581600440,
    'Timezone' => -4,
    'Url' => 'http://prodgame11.alliances.commandandconquer.com/61',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'limitium@gmail.com',
  ),
  62 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => NULL,
    'Id' => 62,
    'Language' => 'en',
    'Name' => 'World 27 (Europe)',
    'StartTime' => 1340118000970,
    'Timezone' => 2,
    'Url' => 'http://prodgame11.alliances.commandandconquer.com/62',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'limitium@gmail.com',
  ),
  64 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots für 25,000 Spieler.',
    'Id' => 64,
    'Language' => 'de',
    'Name' => 'Welt 7',
    'StartTime' => 1340370000970,
    'Timezone' => 2,
    'Url' => 'http://prodgame12.alliances.commandandconquer.com/64',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'limitium@gmail.com',
  ),
  65 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Emplacements pour 25 000 joueurs.',
    'Id' => 65,
    'Language' => 'fr',
    'Name' => 'Monde 3',
    'StartTime' => 1340888400550,
    'Timezone' => 2,
    'Url' => 'http://prodgame12.alliances.commandandconquer.com/65',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  66 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 66,
    'Language' => 'en',
    'Name' => 'World 28 (USA East Coast)',
    'StartTime' => 1340974800570,
    'Timezone' => -4,
    'Url' => 'http://prodgame11.alliances.commandandconquer.com/66',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  67 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 67,
    'Language' => 'en',
    'Name' => 'World 29 (Europe)',
    'StartTime' => 1340974800570,
    'Timezone' => 2,
    'Url' => 'http://prodgame11.alliances.commandandconquer.com/67',
    'x' => 32,
    'y' => 32,
    'u' => 'lworld29@mailinator.com',
    'p' => 'qweqwe123',
  ),
  68 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots für 25,000 Spieler.',
    'Id' => 68,
    'Language' => 'de',
    'Name' => 'Welt 8',
    'StartTime' => 1341579600300,
    'Timezone' => 2,
    'Url' => 'http://prodgame12.alliances.commandandconquer.com/68',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  35 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 35,
    'Language' => 'en',
    'Name' => 'World 30 (Europe)',
    'StartTime' => 1341828000220,
    'Timezone' => 2,
    'Url' => 'http://prodgame03.alliances.commandandconquer.com/35',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  69 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Espacios para 25.000 jugadores.',
    'Id' => 69,
    'Language' => 'es',
    'Name' => 'Mundo 3 (España)',
    'StartTime' => 1342170000260,
    'Timezone' => 2,
    'Url' => 'http://prodgame12.alliances.commandandconquer.com/69',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  70 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 70,
    'Language' => 'en',
    'Name' => 'World 31 (USA West Coast)',
    'StartTime' => 1342288800320,
    'Timezone' => -7,
    'Url' => 'http://prodgame11.alliances.commandandconquer.com/70',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  71 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 71,
    'Language' => 'en',
    'Name' => 'World 32 (USA East Coast)',
    'StartTime' => 1342443600900,
    'Timezone' => -4,
    'Url' => 'http://prodgame11.alliances.commandandconquer.com/71',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  72 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Emplacements pour 25 000 joueurs.',
    'Id' => 72,
    'Language' => 'fr',
    'Name' => 'Monde 4',
    'StartTime' => 1342443600900,
    'Timezone' => 2,
    'Url' => 'http://prodgame12.alliances.commandandconquer.com/72',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  50 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Miejsca dla 25 000 graczy.',
    'Id' => 50,
    'Language' => 'pl',
    'Name' => 'Świat 2',
    'StartTime' => 1342872000920,
    'Timezone' => 2,
    'Url' => 'http://prodgame12.alliances.commandandconquer.com/50',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  73 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => NULL,
    'Id' => 73,
    'Language' => 'en',
    'Name' => 'World 33 (Europe)',
    'StartTime' => 1342623600100,
    'Timezone' => 2,
    'Url' => 'http://prodgame11.alliances.commandandconquer.com/73',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  74 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => NULL,
    'Id' => 74,
    'Language' => 'de',
    'Name' => 'Welt 9',
    'StartTime' => 1342707919870,
    'Timezone' => 2,
    'Url' => 'http://prodgame09.alliances.commandandconquer.com/74',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  75 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => NULL,
    'Id' => 75,
    'Language' => 'ru',
    'Name' => 'Мир 3',
    'StartTime' => 1342707919870,
    'Timezone' => 4,
    'Url' => 'http://prodgame09.alliances.commandandconquer.com/75',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  76 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots für 25,000 Spieler.',
    'Id' => 76,
    'Language' => 'de',
    'Name' => 'Welt 10 ',
    'StartTime' => 1343300400880,
    'Timezone' => 2,
    'Url' => 'http://prodgame06.alliances.commandandconquer.com/76',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  77 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 77,
    'Language' => 'en',
    'Name' => 'World 34 (Europe) ',
    'StartTime' => 1343548800630,
    'Timezone' => 2,
    'Url' => 'http://prodgame11.alliances.commandandconquer.com/77',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  78 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Espaços para 25.000 jogadores.',
    'Id' => 78,
    'Language' => 'pt',
    'Name' => 'Mundo 3 Brazil ',
    'StartTime' => 1343743200200,
    'Timezone' => -3,
    'Url' => 'http://prodgame06.alliances.commandandconquer.com/78',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  79 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 79,
    'Language' => 'en',
    'Name' => 'World 35 (USA East Coast) ',
    'StartTime' => 1343999958660,
    'Timezone' => -4,
    'Url' => 'http://prodgame02.alliances.commandandconquer.com/79',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  80 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots für 25,000 Spieler.',
    'Id' => 80,
    'Language' => 'de',
    'Name' => 'Welt 11  ',
    'StartTime' => 1344074400410,
    'Timezone' => 2,
    'Url' => 'http://prodgame06.alliances.commandandconquer.com/80',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  81 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots for 25,000 players. Rule set: Forgotten boost',
    'Id' => 81,
    'Language' => 'en',
    'Name' => 'World 36 (Europe)  ',
    'StartTime' => 1344502800920,
    'Timezone' => 2,
    'Url' => 'http://prodgame10.alliances.commandandconquer.com/81',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  82 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Espacios para 25.000 jugadores.',
    'Id' => 82,
    'Language' => 'es',
    'Name' => 'Mundo 4 (España) ',
    'StartTime' => 1344510000800,
    'Timezone' => 2,
    'Url' => 'http://prodgame06.alliances.commandandconquer.com/82',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  53 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => '25.000 oyuncu alır',
    'Id' => 53,
    'Language' => 'tr',
    'Name' => 'Dünya 2',
    'StartTime' => 1344866400270,
    'Timezone' => 3,
    'Url' => 'http://prodgame12.alliances.commandandconquer.com/53',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  83 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Ячейки для 25 000 игроков.',
    'Id' => 83,
    'Language' => 'ru',
    'Name' => 'Мир 4',
    'StartTime' => 1344866400270,
    'Timezone' => 4,
    'Url' => 'http://prodgame06.alliances.commandandconquer.com/83',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  84 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Emplacements pour 25 000 joueurs. Règle : Boost des Oubliés',
    'Id' => 84,
    'Language' => 'fr',
    'Name' => 'Monde 5 ',
    'StartTime' => 1345132800900,
    'Timezone' => 2,
    'Url' => 'http://prodgame07.alliances.commandandconquer.com/84',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  85 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots für 25,000 Spieler. Regelset: Vergessenen-Boost',
    'Id' => 85,
    'Language' => 'de',
    'Name' => 'Welt 12   ',
    'StartTime' => 1345374000580,
    'Timezone' => 2,
    'Url' => 'http://prodgame08.alliances.commandandconquer.com/85',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  86 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots for 25,000 players. Rule set: Forgotten boost',
    'Id' => 86,
    'Language' => 'en',
    'Name' => 'World 37 (Europe)',
    'StartTime' => 1345305600230,
    'Timezone' => 2,
    'Url' => 'http://prodgame05.alliances.commandandconquer.com/86',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  87 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots for 25,000 players. Rule set: Forgotten boost',
    'Id' => 87,
    'Language' => 'en',
    'Name' => 'World 38 (USA West Coast)',
    'StartTime' => 1345478400290,
    'Timezone' => -7,
    'Url' => 'http://prodgame03.alliances.commandandconquer.com/87',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  88 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots for 25,000 players. Rule set: Forgotten boost',
    'Id' => 88,
    'Language' => 'en',
    'Name' => 'World 39 (USA East Coast)',
    'StartTime' => 1345478400290,
    'Timezone' => -4,
    'Url' => 'http://prodgame02.alliances.commandandconquer.com/88',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  54 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots voor 25.000 spelers. Regelset: Vergeten bonus',
    'Id' => 54,
    'Language' => 'nl',
    'Name' => 'Wereld 2',
    'StartTime' => 1346083200990,
    'Timezone' => 2,
    'Url' => 'http://prodgame12.alliances.commandandconquer.com/54',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  99 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Espaços para 25.000 jogadores. Conjunto de regras: melhoria dos Esquecidos\'',
    'Id' => 99,
    'Language' => 'br',
    'Name' => 'Mundo 4 Brazil  ',
    'StartTime' => 1346083200990,
    'Timezone' => -3,
    'Url' => 'http://prodgame08.alliances.commandandconquer.com/99',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  100 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots for 25,000 players. Rule set: Forgotten boost',
    'Id' => 100,
    'Language' => 'en',
    'Name' => 'World 40 (Europe) ',
    'StartTime' => 1346417336460,
    'Timezone' => 2,
    'Url' => 'http://prodgame05.alliances.commandandconquer.com/100',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  101 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots für 25,000 Spieler. Regelset: Vergessenen-Boost',
    'Id' => 101,
    'Language' => 'de',
    'Name' => 'Welt 13    ',
    'StartTime' => 1346691600990,
    'Timezone' => 2,
    'Url' => 'http://prodgame06.alliances.commandandconquer.com/101',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  102 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Espacios para 25.000 jugadores.',
    'Id' => 102,
    'Language' => 'es',
    'Name' => 'Mundo 5 (España)  ',
    'StartTime' => 1347469200830,
    'Timezone' => 2,
    'Url' => 'http://prodgame08.alliances.commandandconquer.com/102',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  103 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Miejsca dla 25 000 graczy.',
    'Id' => 103,
    'Language' => 'pl',
    'Name' => 'Świat 3 ',
    'StartTime' => 1347469200850,
    'Timezone' => 2,
    'Url' => 'http://prodgame08.alliances.commandandconquer.com/103',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  104 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots for 25,000 players. Rule set: Forgotten boost',
    'Id' => 104,
    'Language' => 'en',
    'Name' => 'World 41 (Europe) ',
    'StartTime' => 1347469200850,
    'Timezone' => 2,
    'Url' => 'http://prodgame02.alliances.commandandconquer.com/104',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  51 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Entradas para 25 000 jogadores.',
    'Id' => 51,
    'Language' => 'pt',
    'Name' => 'Mundo 2 (Portuguesa)',
    'StartTime' => 1347984000320,
    'Timezone' => 1,
    'Url' => 'http://prodgame12.alliances.commandandconquer.com/51',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  105 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots für 25,000 Spieler. Regelset: Vergessenen-Boost',
    'Id' => 105,
    'Language' => 'de',
    'Name' => 'Welt 14     ',
    'StartTime' => 1347638400980,
    'Timezone' => 2,
    'Url' => 'http://prodgame07.alliances.commandandconquer.com/105',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  106 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots for 25,000 players. Rule set: Forgotten boost',
    'Id' => 106,
    'Language' => 'en',
    'Name' => 'World 42 (USA East Coast) ',
    'StartTime' => 1347638400980,
    'Timezone' => -4,
    'Url' => 'http://prodgame02.alliances.commandandconquer.com/106',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  107 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Ячейки для 25 000 игроков.',
    'Id' => 107,
    'Language' => 'ru',
    'Name' => 'Мир 5  ',
    'StartTime' => 1347984000320,
    'Timezone' => 4,
    'Url' => 'http://prodgame08.alliances.commandandconquer.com/107',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  108 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots for 25,000 players. Rule set: Forgotten boost',
    'Id' => 108,
    'Language' => 'en',
    'Name' => 'World 43 (Europe)  ',
    'StartTime' => 1348240900440,
    'Timezone' => 2,
    'Url' => 'http://prodgame10.alliances.commandandconquer.com/108',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  109 => 
  array (
    'AcceptNewPlayer' => true,
    'Changelist' => 372798,
    'Description' => 'Emplacements pour 25 000 joueurs. Règle : Boost des Oubliés',
    'Id' => 109,
    'Language' => 'fr',
    'Name' => 'Monde 6  ',
    'StartTime' => 1348596000830,
    'Timezone' => 2,
    'Url' => 'http://prodgame09.alliances.commandandconquer.com/109',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  110 => 
  array (
    'AcceptNewPlayer' => true,
    'Changelist' => 372798,
    'Description' => 'Slots für 25,000 Spieler. Regelset: Vergessenen-Boost',
    'Id' => 110,
    'Language' => 'de',
    'Name' => 'Welt 15      ',
    'StartTime' => 1348596000830,
    'Timezone' => 2,
    'Url' => 'http://prodgame09.alliances.commandandconquer.com/110',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  121 => 
  array (
    'AcceptNewPlayer' => true,
    'Changelist' => 372567,
    'Description' => 'Slots for 25,000 players. Rule set: Forgotten boost',
    'Id' => 121,
    'Language' => 'en',
    'Name' => 'World 44 (Europe)   ',
    'StartTime' => 1349110800370,
    'Timezone' => 2,
    'Url' => 'http://prodgame03.alliances.commandandconquer.com/121',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  122 => 
  array (
    'AcceptNewPlayer' => true,
    'Changelist' => 372798,
    'Description' => 'Ячейки для 25 000 игроков.',
    'Id' => 122,
    'Language' => 'ru',
    'Name' => 'Мир 6   ',
    'StartTime' => 1349110800370,
    'Timezone' => 4,
    'Url' => 'http://prodgame14.alliances.commandandconquer.com/122',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  123 => 
  array (
    'AcceptNewPlayer' => true,
    'Changelist' => 373715,
    'Description' => 'Slots für 25,000 Spieler. Regelset: Vergessenen-Boost',
    'Id' => 123,
    'Language' => 'de',
    'Name' => 'Welt 16       ',
    'StartTime' => 1349701200190,
    'Timezone' => 2,
    'Url' => 'http://prodgame14.alliances.commandandconquer.com/123',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  124 => 
  array (
    'AcceptNewPlayer' => true,
    'Changelist' => 373715,
    'Description' => 'Slots for 25,000 players. Rule set: Forgotten boost',
    'Id' => 124,
    'Language' => 'en',
    'Name' => 'World 45 (USA West Coast) ',
    'StartTime' => 1349701200190,
    'Timezone' => -7,
    'Url' => 'http://prodgame02.alliances.commandandconquer.com/124',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  125 => 
  array (
    'AcceptNewPlayer' => true,
    'Changelist' => 373715,
    'Description' => 'Slots for 25,000 players. Rule set: Forgotten boost',
    'Id' => 125,
    'Language' => 'en',
    'Name' => 'World 46 (USA East Coast)  ',
    'StartTime' => 1349701200190,
    'Timezone' => -4,
    'Url' => 'http://prodgame03.alliances.commandandconquer.com/125',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  126 => 
  array (
    'AcceptNewPlayer' => true,
    'Changelist' => 373715,
    'Description' => 'Espacios para 25.000 jugadores.',
    'Id' => 126,
    'Language' => 'es',
    'Name' => 'Mundo 6 (España)   ',
    'StartTime' => 1349701200190,
    'Timezone' => 2,
    'Url' => 'http://prodgame13.alliances.commandandconquer.com/126',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  127 => 
  array (
    'AcceptNewPlayer' => true,
    'Changelist' => 373715,
    'Description' => 'Slots for 25,000 players. Rule set: Forgotten boost',
    'Id' => 127,
    'Language' => 'en',
    'MaxPlayers' => 25000,
    'Name' => 'World 47 (Europe)    ',
    'StartTime' => 1350028800140,
    'Timezone' => 2,
    'Url' => 'http://prodgame02.alliances.commandandconquer.com/127',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  128 => 
  array (
    'AcceptNewPlayer' => true,
    'Changelist' => 373715,
    'Description' => 'Entradas para 25 000 jogadores.',
    'Id' => 128,
    'Language' => 'pt',
    'MaxPlayers' => 25000,
    'Name' => 'Mundo 3 (Portuguesa) ',
    'StartTime' => 1350028800150,
    'Timezone' => 1,
    'Url' => 'http://prodgame07.alliances.commandandconquer.com/128',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  129 => 
  array (
    'AcceptNewPlayer' => true,
    'Changelist' => 373715,
    'Description' => 'Miejsca dla 25 000 graczy.',
    'Id' => 129,
    'Language' => 'pl',
    'MaxPlayers' => 25000,
    'Name' => 'Świat 4  ',
    'StartTime' => 1350919800500,
    'Timezone' => 2,
    'Url' => 'http://prodgame13.alliances.commandandconquer.com/129',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  130 => 
  array (
    'AcceptNewPlayer' => true,
    'Changelist' => 373715,
    'Description' => 'Slots für 25,000 Spieler. Regelset: Vergessenen-Boost',
    'Id' => 130,
    'Language' => 'de',
    'MaxPlayers' => 25000,
    'Name' => 'Welt 17        ',
    'StartTime' => 1350895496770,
    'Timezone' => 2,
    'Url' => 'http://prodgame13.alliances.commandandconquer.com/130',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  131 => 
  array (
    'AcceptNewPlayer' => true,
    'Changelist' => 373715,
    'Description' => 'Ячейки для 25 000 игроков.',
    'Id' => 131,
    'Language' => 'ru',
    'MaxPlayers' => 25000,
    'Name' => 'Мир 7    ',
    'StartTime' => 1350895496770,
    'Timezone' => 4,
    'Url' => 'http://prodgame13.alliances.commandandconquer.com/131',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  132 => 
  array (
    'AcceptNewPlayer' => true,
    'Changelist' => 376345,
    'Description' => 'Slots for 25,000 players. Rule set: Forgotten boost',
    'Id' => 132,
    'Language' => 'en',
    'MaxPlayers' => 25000,
    'Name' => 'World 48 (Europe)     ',
    'StartTime' => 1350914491840,
    'Timezone' => 2,
    'Url' => 'http://prodgame05.alliances.commandandconquer.com/132',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  48 => 
  array (
    'AcceptNewPlayer' => true,
    'Changelist' => 377320,
    'Description' => 'Slot per 25.000 giocatori.',
    'Id' => 48,
    'Language' => 'it',
    'MaxPlayers' => 25000,
    'Name' => 'Mondo 2',
    'StartTime' => 1351501200610,
    'Timezone' => 1,
    'Url' => 'http://prodgame12.alliances.commandandconquer.com/48',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  133 => 
  array (
    'AcceptNewPlayer' => true,
    'Changelist' => 377320,
    'Description' => 'Slots for 25,000 players. Rule set: Forgotten boost',
    'Id' => 133,
    'Language' => 'en',
    'MaxPlayers' => 25000,
    'Name' => 'World 49 (USA East Coast)   ',
    'StartTime' => 1351242000810,
    'Timezone' => -4,
    'Url' => 'http://prodgame05.alliances.commandandconquer.com/133',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  134 => 
  array (
    'AcceptNewPlayer' => true,
    'Changelist' => 377320,
    'Description' => 'Emplacements pour 25 000 joueurs. Règle : Boost des Oubliés',
    'Id' => 134,
    'Language' => 'fr',
    'MaxPlayers' => 25000,
    'Name' => 'Monde 7   ',
    'StartTime' => 1.35186120039E+12,
    'Timezone' => 1,
    'Url' => 'http://prodgame13.alliances.commandandconquer.com/134',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  136 => 
  array (
    'AcceptNewPlayer' => true,
    'Changelist' => 377320,
    'Description' => 'Entradas para 25 000 jogadores.',
    'Id' => 136,
    'Language' => 'pt',
    'MaxPlayers' => 25000,
    'Name' => 'Mundo 4 (Portuguesa)  ',
    'StartTime' => 1.35186120039E+12,
    'Timezone' => 0,
    'Url' => 'http://prodgame12.alliances.commandandconquer.com/136',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  137 => 
  array (
    'AcceptNewPlayer' => true,
    'Changelist' => 377320,
    'Description' => 'Slots für 25,000 Spieler. Regelset: Vergessenen-Boost',
    'Id' => 137,
    'Language' => 'de',
    'MaxPlayers' => 25000,
    'Name' => 'Welt 18         ',
    'StartTime' => 1.35186120039E+12,
    'Timezone' => 1,
    'Url' => 'http://prodgame06.alliances.commandandconquer.com/137',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  138 => 
  array (
    'AcceptNewPlayer' => true,
    'Changelist' => 377320,
    'Description' => 'Slots for 25,000 players. Rule set: Forgotten boost',
    'Id' => 138,
    'Language' => 'en',
    'MaxPlayers' => 25000,
    'Name' => 'World 50 (Europe)      ',
    'StartTime' => 1.35186120039E+12,
    'Timezone' => 1,
    'Url' => 'http://prodgame03.alliances.commandandconquer.com/138',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
  139 => 
  array (
    'AcceptNewPlayer' => true,
    'Changelist' => 377320,
    'Description' => 'Espacios para 25.000 jugadores.',
    'Id' => 139,
    'Language' => 'es',
    'MaxPlayers' => 25000,
    'Name' => 'Mundo 7 (España)    ',
    'StartTime' => 1.35186120039E+12,
    'Timezone' => 1,
    'Url' => 'http://prodgame07.alliances.commandandconquer.com/139',
    'x' => 32,
    'y' => 32,
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
  ),
);